all:
	make -C composer
	make -C context
	make -C database
	make -C loader
	make -C search
	make -C search_extra
	make -C sign_properties
	make -C signlist

install:
	make -C composer install
	make -C context install
	make -C database install
	make -C loader install
	make -C search install
	make -C search_extra install
	make -C sign_properties install
	make -C signlist install