all:
	make -C actions
	make -C citation
	make -C composer
	make -C context
	make -C database
	make -C editor
	make -C encoder
	make -C encode_corpus
	make -C loader
	make -C parser
	make -C replace
	make -C search
	make -C search_extra
	make -C sign_properties
	make -C signlist
	make -C test

install:
	make -C actions install
	make -C citation install
	make -C composer install
	make -C context install
	make -C database install
	make -C editor install
	make -C encoder install
	make -C encode_corpus install
	make -C loader install
	make -C parser install
	make -C replace install
	make -C search install
	make -C search_extra install
	make -C sign_properties install
	make -C signlist install
	make -C test install